### PR TITLE
Feature/api endpoints fix

### LINKED ISSUE #3: Feature: API Endpoints
Add REST endpoints (health/users)

Create controller/service structure

Return JSON with status codes

Update docs/README

### PR DESCRIPTION
**Pull request by stripathi6**
Closes  #3

Summary
- Added POST /api/echo endpoint with validation
- Added /api/version endpoint
- Mounted /api/auth routes in api.js
- Added docs/api-endpoints.md documentation

Testing
- Ran locally using npm install and npm run dev
- Verified GET /api/health works
- Verified POST /api/echo returns 200 and validates input

### CODE REVIEW

File: src/routes/api.js [hunk 1]
```diff
@@ -11,9 +11,14 @@ const authRouter = require("./auth.routes");
  */
 
 router.get("/health", (req, res) => {
-  res.json({ status: "ok", time: new Date().toISOString() });
+  res.json({
+    ok: true,
+    data: { status: "ok", time: new Date().toISOString() },
+    error: null,
+  });
```
Comment (stripathi6) [inline src/routes/api.js:18]: Nice improvement 👍
Can we add a short comment above /api/echo explaining what it’s used for (demo validation + request body example)?

File: docs/api-endpoints.md [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+### GET /api/health
+Returns a basic health response.
+
+### GET /api/version
+Returns app version and environment info.
+
+### POST /api/auth/login
+Stub login endpoint for checkpoint testing.
+
```
Comment (stripathi6) [inline docs/api-endpoints.md:24]: Looks good ✅
Please add one more example showing how to test /api/echo in the browser using Postman OR curl.

**Review by stripathi6 — COMMENTED** [review]
Requested changes ✅

Please:
1) Add a short comment in api.js explaining the /api/echo endpoint purpose.
2) Add one testing example in docs/api-endpoints.md (curl OR Postman).

After that, PR will be ready to merge 👍
